### ISSUE TITLE
【管理者画面】Auth実装

### ISSUE THREAD

**Issue by UNILORN** [UNILORN/OIC_Book#100]

**Comment by chiii** [comment]
このAuth実装ってどういう意味？

**Comment by UNILORN** [comment]
いま、管理者じゃなくてもそのままはいれちゃうから、ログイン機能を実装してほしい

**Comment by chiii** [comment]
それまるちおーすじゃないの？

**Comment by UNILORN** [comment]
そそ。ただ、マルチオース出来ても、管理者ページ全部にログイン許可を与えるのは別やと考えてるから、分けていしゅーにしてる。

**Comment by chiii** [comment]
それは、権限つけるってことですか？

**Comment by UNILORN** [comment]
権限は無し。
管理者ページは複数あるから、そのページ全部にマルチオースのチェックをかけないと、商品詳細はログインしないと見れないけど、発注情報は普通にみれちゃう。なんてことはいけないから、マルチオースの実装ができたらページに付け加える方向でお願いします

**Comment by chiii** [comment]
なるふぉい
