### ISSUE TITLE
【提出書類】画面遷移図

### ISSUE THREAD

**Issue by UNILORN** [UNILORN/OIC_Book#107]
https://drive.google.com/drive/u/2/folders/0Bz6hafVm8ouMbHota0pRT0VmMXc

**Comment by UNILORN** [comment]
画面遷移図はできるだけ次の授業までにある程度完成してほしいです。

**Comment by sizukutamago** [comment]
https://drive.google.com/drive/folders/0Bz6hafVm8ouMbHota0pRT0VmMXc
