### ISSUE TITLE
コード設計書

### ISSUE THREAD

**Issue by Serorin** [UNILORN/OIC_Book#35]

**Comment by kamonedo** [comment]
MultiAuthについて確認がとれていないので保留中です。
また，USERテーブルを含む各テーブルでNULLを許可するものと許可しないものがはっきりとしていません。
現在の成果物に沿って修正が必要かどうか相談する必要があります。

**Comment by kamonedo** [comment]
テーブル仕様書が完成し次第，書類の修正・加筆を始めます。

**Comment by UNILORN** [comment]
https://drive.google.com/drive/u/2/folders/0Bz6hafVm8ouMNTktWi1HQnBtVXc

**Comment by kamonedo** [comment]
現実的な件数にする
