### ISSUE TITLE
テーブル仕様書

### ISSUE THREAD

**Issue by Serorin** [UNILORN/OIC_Book#36]

**Comment by kamonedo** [comment]
MultiAuthについて確認がとれていないので保留中です。
また，USERテーブルを含む各テーブルでNULLを許可するものと許可しないものがはっきりとしていません。
さらに現在の成果物に沿って修正する箇所があるかどうか見直しが必要です。

**Comment by kamonedo** [comment]
サイズ見直し必須

**Comment by UNILORN** [comment]
https://drive.google.com/drive/u/2/folders/0Bz6hafVm8ouMSTNDZnZYcnpQRTA
