### ISSUE TITLE
【提出書類】URL表

### ISSUE THREAD

**Issue by Serorin** [UNILORN/OIC_Book#39]

**Comment by kamonedo** [comment]
Googleドライブ上の「M_URL設計表」に今まで作成されたURL関連のファイルをまとめました。
[https://drive.google.com/open?id=0B_T_639i-zYSSXZ2dEg3X0pGUkE](url)

**Comment by UNILORN** [comment]
https://docs.google.com/spreadsheets/d/1eVoiyx6C62E7qrfaspV6bHZACZ11U4uonfF4UCeNgSU/edit#gid=0

**Comment by UNILORN** [comment]
テンプレ作りました。　暇な人やってください
