### ISSUE TITLE
<<画面一覧をどなたか作成してください>>

### ISSUE THREAD

**Issue by UNILORN** [UNILORN/OIC_Book#83]

**Comment by UNILORN** [comment]
現段階での画面一覧です。
早急に作成してください。

**Comment by chiii** [comment]
【メイン】
トップ
マイページ
カート
商品一覧
商品明細
ログイン
新規登録
buy
購入履歴
ポイント履歴
購入確認画面


【管理者】
商品情報
従業員情報
ユーザー情報
売上情報
発注情報
入庫情報
入金情報
発注先メールフォーム
入荷登録フォーム


※追加あれば、コメントで追加していきます

**Comment by kamonedo** [comment]
Googleドライブ内の「M_画面設計書」に「画面一覧(仮)」を作成しました。
